[workspace]
# include a member for each contract
members = [
  "sputnik-staking",
  "sputnikdao2",
  "sputnikdao-factory2",
<<<<<<< HEAD
  "test-token",
  "voting"
=======
  "test-token"
>>>>>>> 4c04023d81c526af92d771dc71a1f2216de3f45c
]

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = true
panic = "abort"
# Opt into extra safety checks on arithmetic operations https://stackoverflow.com/a/64136471/249801
overflow-checks = true
